# 1. 데이터 경로 설정
data_path: "C:/blooming_AI/classification_dataset" # 데이터셋 상위 폴더 경로
annotation_path: "C:/blooming_AI/classification_annotation" # 라벨 폴더

# 2. 모델 설정 (DINOv2 공식 정보)
model_repo: "facebookresearch/dinov2" # ✅ DINOv2 공식 리포지토리
model_name: "dinov2_vits14"            # ✅ DINOv2 ViT-Small의 정확한 이름 (patch size 14)
# model_name: "deit_tiny_patch16_224"
num_classes: 3 
freeze_backbone: true

# 3. 학습 하이퍼파라미터
epochs: 20
batch_size: 64 
learning_rate: 0.001

# 4. 실행 환경 설정
device: "cuda"
